version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: leahewing
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      # POSTGRES_HOST: "/tmp/"
    ports:
      - "5433:5433"