name: HolidayHub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Create encryption files
        run: |
           mkdir ${{ secrets.ENCRYPTION_DIRECTORY }}
           touch ${{ secrets.ENCRYPTION_PATH }}
           touch ${{ secrets.VALID_ENCRYPTION_KEYS_PATH }}
           touch ${{ secrets.ENCRYPTION_DICT_PATH }}

      - name: Import encryption code
        run: |
           echo "${{ secrets.ENCRYPTION_SCRIPT }}" > ${{ secrets.ENCRYPTION_PATH }}
           echo "${{ secrets.VALID_ENCRYPTION_KEYS }}" > ${{ secrets.VALID_ENCRYPTION_KEYS_PATH }}
           echo "${{ secrets.ENCRYPTION_DICTIONARY }}" > ${{ secrets.ENCRYPTION_DICT_PATH }}


      - name: Generate Docker Compose file and create database
        run: |
            ./generate-compose.sh ${{ secrets.DB_NAME }}
            sleep 10

      - name: Seed database
        run: |
          python3 database/seed_database.py
          python3 database/seed_holidays.py
          python3 database/run_migrations.py
          
      - name: Start jobs
        run: |
            python3 jobs/run_jobs.py

      - name: Start Flask app using Gunicorn
        run: |
            gunicorn -b 0.0.0.0:8000 server:app