name: HolidayHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Generate Docker Compose file
        run: ./generate-compose.sh
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: leahewing

      - name: Setup database
        run: |
          createdb ${{ secrets.DB_NAME }}
          python3 database/seed_database.py
          python3 database/seed_holidays.py
          python3 database/run_migrations.py
          
      - name: Start Jobs
        run: |
            python3 jobs/run_jobs.py

      - name: Start Flask app using Gunicorn
        run: |
            gunicorn -b 0.0.0.0:8000 server:app
